#output directory
output_dir: /path/to/output/dir

# dir with genome fasta files, must have '.fasta' extension, to convert use 'rename .fa .fasta  *.fa' (e.g. if extensions are .fa)
genome_fasta: /path/to/genome/fasta/dir

# path to bakta DB:
bakta_db: path/to/bakta/db/dir

# path to checkm2 db
checkm2_db: path/to/checkm2/db/dir

# cgt executable parameters
cgt_exe: /path/to/cgt/exe
cgt_breaks: 0.05,0.95
cgt_error: 0.05

# choice of checkm method, either "checkm1" or "checkm2"
checkm_method: "checkm2"

# choice of clustering method, either "mmseqs2" or "panaroo"
clustering_method: "panaroo"

# must be one of "strict", "moderate" or "sensitive"
panaroo_stringency: "strict"